version: "3.1"
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

# Define the NLU pipeline
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper

# Define the core policies
policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20241211-183522-giant-paradigm