services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.2
    environment:
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://text2vec-transformers:8080
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/data"
    ports:
      - "8080:8080"
      - "50051:50051"  # Bind gRPC to the host
    depends_on:
      - text2vec-transformers
  
  text2vec-transformers:
    image: cr.weaviate.io/semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: "0"
    ports:
      - "8081:8080"
