FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV HUGGINGFACE_API_KEY="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"

EXPOSE 5000
CMD ["python", "app.py"]
