name: Deploy Frontend (Angular)

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to AWS ECR (Frontend)
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_FRONTEND_URI }}

      - name: Build & Push Frontend Docker Image
        run: |
          docker build -t scope3-mvp-frontend -f ./frontend/Dockerfile.frontend ./frontend
          docker tag scope3-mvp-frontend:latest ${{ secrets.ECR_FRONTEND_URI }}:latest
          docker push ${{ secrets.ECR_FRONTEND_URI }}:latest

      - name: Deploy Frontend to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_FRONTEND_URI }}
            docker stop scope3-frontend || true && docker rm scope3-frontend || true
            docker pull ${{ secrets.ECR_FRONTEND_URI }}:latest
            docker run -d -p 80:80 --name scope3-frontend ${{ secrets.ECR_FRONTEND_URI }}:latest
