name: Deploy Backend (Node.js)

on:
  push:
    branches:
      - main
      - development
      - feature/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin <ECR_URI_BACKEND>

      - name: Build & Push Backend Docker Image
        run: |
          docker build -t scope3-mvp-backend -f ./backend/Dockerfile.backend .
          docker tag scope3-mvp-backend:latest <ECR_URI_BACKEND>:latest
          docker push <ECR_URI_BACKEND>:latest

      - name: Deploy to EC2 via SSH (backend)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop scope3-backend || true && docker rm scope3-backend || true
            docker pull <ECR_URI_BACKEND>:latest
            docker run -d -p 3000:3000 --name scope3-backend <ECR_URI_BACKEND>:latest
